### ISSUE TITLE
Port all test cases to Jest tests

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/inchi#13]
Refer to https://github.com/kulshekhar/ts-jest for details.

**Comment by maneetgoyal** [comment]
@saikat-samanta You can start on this.

**Comment by maneetgoyal** [comment]
The test cases present here (https://github.com/manufac-analytics/inchi/tree/main/tests) should be ported into Jest-style test cases.

**Comment by maneetgoyal** [comment]
@saikat-samanta What updates do you have here?

**Comment by saikat-samanta** [comment]
I will start working on it from now on
