### ISSUE TITLE
Dereference objects properly

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/inchi#24]
Refer to https://github.com/manufac-analytics/inchi/pull/22#discussion_r696554256

---

Task list:

- [x] Struct need to be corrected
- [x] TS interfaces need to be corrected
- [x] `headers.test.ts` needs to checked and updated (if needed)
- [x] `deref.ts` needs to be updated
- [x] `api.ts` needs to be updated
- [x] `api.test.ts` needs to be updated

**Comment by qur786** [comment]
> @qur786 We can discuss more over call in the morning.

sure sir

**Comment by qur786** [comment]
@maneetgoyal sir this issue has been solved , but there is problem with the atom and strereo0D as I mentioned to you. Should I close it or leave it as open.

**Comment by maneetgoyal** [comment]
@qur786 Sorry I can't recall the problem. What is it?

**Comment by maneetgoyal** [comment]
Oh sorry, related to test cases?

**Comment by qur786** [comment]
> Oh sorry, related to test cases?
sir we are getting empty atom array and stereo array when we are fetching data using GetStructXYZ

**Comment by maneetgoyal** [comment]
> sir we are getting empty atom array and stereo array when we are fetching data using GetStructXYZ

That is okay for now. Lets try to implement #25, and close this one.

**Comment by qur786** [comment]
the task is completed
