### ISSUE TITLE
Test and have better error handling in server.ts functions

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/inchi#41]
<h3 id="error_object" style="margin: 0px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; color: rgb(51, 51, 51); text-rendering: optimizelegibility; line-height: 27px; font-size: 18px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">5.1 Error object</h3><p style="margin: 0px 0px 9px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">When a rpc call encounters an error, the Response Object MUST contain the error member with a value that is a Object with the following members:</p><dl style="margin-bottom: 18px; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><dt style="line-height: 17px; font-weight: bold;">code</dt><dd style="line-height: 18px; margin-left: 9px;">A Number that indicates the error type that occurred.<br>This MUST be an integer.</dd><dt style="line-height: 17px; font-weight: bold;">message</dt><dd style="line-height: 18px; margin-left: 9px;">A String providing a short description of the error.<br>The message SHOULD be limited to a concise single sentence.</dd><dt style="line-height: 17px; font-weight: bold;">data</dt><dd style="line-height: 18px; margin-left: 9px;">A Primitive or Structured value that contains additional information about the error.<br>This may be omitted.<br>The value of this member is defined by the Server (e.g. detailed error information, nested errors etc.).</dd></dl><p style="margin: 0px 0px 9px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The error codes from and including -32768 to -32000 are reserved for pre-defined errors. Any code within this range, but not defined explicitly below is reserved for future use. The error codes are nearly the same as those suggested for XML-RPC at the following url:<span> </span><a href="http://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php" style="color: rgb(0, 136, 204); text-decoration: none;">http://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php</a></p>

code | message | meaning
-- | -- | --
-32700 | Parse error | Invalid JSON was received by the server.An error occurred on the server while parsing the JSON text.
-32600 | Invalid Request | The JSON sent is not a valid Request object.
-32601 | Method not found | The method does not exist / is not available.
-32602 | Invalid params | Invalid method parameter(s).
-32603 | Internal error | Internal JSON-RPC error.
-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

<p style="margin: 0px 0px 9px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The remainder of the space is available for application defined errors.</p>

Ref: https://www.jsonrpc.org/specification

**Comment by qur786** [comment]
CheckINCHIKey
![image](https://user-images.githubusercontent.com/79472606/131887088-d600c9d2-9afc-4586-8c04-9f7caf82ff7d.png)

**Comment by qur786** [comment]
CheckINCHI
![image](https://user-images.githubusercontent.com/79472606/131887421-6afe1c8c-ad00-4918-876b-c22730fa45f2.png)

**Comment by qur786** [comment]
GetStringLength
![image](https://user-images.githubusercontent.com/79472606/131887663-736387b8-a379-461b-a893-b4645956ba7d.png)

**Comment by qur786** [comment]
GetStructFromINCHI
![image](https://user-images.githubusercontent.com/79472606/131888178-2981f1d9-191e-49c5-845b-d13a663a1a78.png)

**Comment by qur786** [comment]
GetStructINCHIEx
![image](https://user-images.githubusercontent.com/79472606/131888364-e178e224-b206-4e21-a82b-76f5f8e3c930.png)

**Comment by qur786** [comment]
GetStructFromStdINCHI
![image](https://user-images.githubusercontent.com/79472606/131888642-d715504b-d3fe-40a1-af74-5c37df3288ae.png)

**Comment by qur786** [comment]
error is handled properly and the functions have been tested .
