### ISSUE TITLE
Successfully build the source code

### ISSUE THREAD

**Issue by maneetgoyal** [manufac-analytics/inchi#52]
@MBhavishya @koustavpan You may have already cloned the repo by now. Going further, the task is to compile/build and test that source code by running:

```
yarn build
yarn test
```

in the terminal.

Seek help from @qur786 in order to set up the development environment if needed.

Setting up the VSCode dev container is a convenient way to move forward. Ref: https://code.visualstudio.com/docs/remote/containers. It involves installing Docker.

You may want to refer to https://github.com/manufac-analytics/inchi#how-to-use-this-library as well if you can't install Docker for some reason. Low RAM (<= 4 GB) may not work well with Docker.

---

Please comment on this issue when you are done.

**Comment by koustavpan** [comment]
Successfully ran the yarn build and test commands.

**Comment by MBhavishya** [comment]
> Successfully ran the yarn build and test commands.

Done with issued task, successfully ran the commands.
